image: node:16-alpine

variables:
  DOMAIN: catex
  REPOSITORY: gigapress
  TAG_VERSION_REGEX: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

stages:
  - build
  - delivery

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - node_modules/
    - .pnpm-store

build:
  stage: build
  before_script:
    - export NODE_OPTIONS=--max_old_space_size=4096
    - node -v
    - apk add --no-cache curl
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
    - pnpm -v
    - pnpm install
  script:
    - pnpm -r build
  artifacts:
    expire_in: 1 hour
    paths:
      - packages/**/dist
    exclude:
      - packages/**/node_modules/**/*
    when: on_success
  only:
    refs:
      - branches
      - tags
      - TAG_VERSION_REGEX

.publish:
  stage: delivery
  variables:
    AWS_PROFILE: catex
    AWS_REGION: eu-north-1
  before_script:
    - apk add --no-cache curl
    - apk add --no-cache python3 py3-pip
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm -v
    - pnpm install
    - pip install awscli
    - aws codeartifact login --region $AWS_REGION --tool npm --domain $DOMAIN --repository $REPOSITORY
  dependencies:
    - build
  cache: []

publish-dev:
  extends: .publish
  script:
    - pnpm add-suffix
    - pnpm -r publish
  only:
    - dev

publish-prod:
  extends: .publish
  script:
    - pnpm -r publish
  only:
    - tags
    - TAG_VERSION_REGEX
