import { defineWidget } from '../../utils/define-extension';

export default defineWidget({
	id: 'richText',
	name: 'Rich Text',
	icon: 'chat',
	options: [
		{
			field: 'content',
			name: 'Rich Text',
			type: 'string',
			meta: {
				required: true,
				interface: 'input-rich-text-html',
				width: 'full',
				options: {
					trim: true,
					placeholder: 'Enter content here',
					toolbar: [
						'undo',
						'redo',
						'bold',
						'italic',
						'underline',
						'strikethrough',
						'fontselect',
						'fontsizeselect',
						'h1',
						'h2',
						'h3',
						'h4',
						'h5',
						'h6',
						'aligncenter',
						'alignjustify',
						'alignleft',
						'alignnone',
						'alignright',
						'outdent',
						'indent',
						'bullist',
						'numlist',
						'backcolor',
						'forecolor',
						'removeformat',
						'code',
						'customImage',
						'customMedia',
						'customLink',
					],
				},
			},
		},
	],
});
